version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092

#  hepsiburada_realtime_recommendation_service_view_producer_app:
#    image: docker-spring-boot:latest
#    build: ./view-producer-app
#    ports:
#      - "8001:8001"
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    depends_on:
#      - kafka
#    networks:
#      - hepsiburada_realtime_recommendation_service_network
#
#  hepsiburada_realtime_recommendation_service_app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: ./api
#    container_name: hepsiburada_realtime_recommendation_service_app
#    depends_on:
#      - hepsiburada_realtime_recommendation_service_db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123456
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://hepsiburada_realtime_recommendation_service_db:5432/hepsiburada_realtime_recommendation_service_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=123456
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    ports:
#      - "8002:8002"
#    networks:
#      - hepsiburada_realtime_recommendation_service_network
#
  hepsiburada_realtime_recommendation_service_db:
    image: postgres:latest
    container_name: hepsiburada_realtime_recommendation_service_db
    environment:
      POSTGRES_DB: hepsiburada_realtime_recommendation_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
#    networks:
#      - hepsiburada_realtime_recommendation_service_network

#networks:
#  hepsiburada_realtime_recommendation_service_network:
#    driver: bridge